// TODO: types of reminder
export const FETCH_REMINDER = 'FETCH_REMINDER';
export const FETCH_REMINDER_SUCCESS = 'FETCH_REMINDER_SUCCESS';
export const FETCH_REMINDER_FAILURE = 'FETCH_REMINDER_FAILURE';

export const SET_REMINDER = 'SET_REMINDER';
export const SET_REMINDER_SUCCESS = 'SET_REMINDER_SUCCESS';
export const SET_REMINDER_FAILURE = 'SET_REMINDER_FAILURE';

export const DELETE_REMINDER = 'DELETE_REMINDER';
export const DELETE_REMINDER_SUCCESS = 'DELETE_REMINDER_SUCCESS';
export const DELETE_REMINDER_FAILURE = 'DELETE_REMINDER_FAILURE';

export const UPDATE_REMINDER = 'UPDATE_REMINDER';
export const UPDATE_REMINDER_SUCCESS = 'UPDATE_REMINDER_SUCCESS';
export const UPDATE_REMINDER_FAILURE = 'UPDATE_REMINDER_FAILURE';
